import { Bill } from "./types";

// Curated list of bills relevant to Altadena/Eaton Fire recovery, wildfire law in California,
// and federal disaster/FEMA legislation. Statuses reflect information available as of early 2025.
// Users should click through to source links for current status.

export const CURATED_BILLS: Bill[] = [
  // ── CALIFORNIA EMERGENCY SESSION (2025) ─────────────────────────────────────

  {
    id: "ca-abx2-1",
    billNumber: "ABX2 1",
    title: "Wildfire Debris Removal and Recovery Assistance",
    description:
      "Authorizes accelerated debris removal programs for properties damaged by the 2025 Los Angeles wildfires, including the Eaton Fire in Altadena. Streamlines state contracting and liability rules for debris cleanup contractors.",
    source: "california",
    status: "signed",
    statusLabel: "Signed into Law",
    statusDate: "2025-02-01",
    introducedDate: "2025-01-14",
    body: "California Assembly – Second Extraordinary Session",
    sponsors: [
      { name: "Gabriel", party: "D" },
      { name: "Alvarez", party: "D" },
    ],
    topics: ["debris_removal", "wildfire_recovery", "disaster_relief"],
    url: "https://leginfo.legislature.ca.gov/faces/billTextClient.xhtml?bill_id=202520260ABX21",
    summary:
      "Part of California's emergency legislative response to the January 2025 Los Angeles fires, this bill creates expedited pathways for government-sponsored debris removal, waiving some standard procurement rules to accelerate cleanup.",
    lastAction: "Signed by Governor Newsom",
    isHighlighted: true,
    relevanceScore: 10,
  },
  {
    id: "ca-sbx2-1",
    billNumber: "SBX2 1",
    title: "Emergency Wildfire Response: State Assistance and Coordination",
    description:
      "Provides emergency supplemental appropriations and coordination authority for the state's response to the 2025 Los Angeles fires, including the Eaton Fire, Palisades Fire, and other concurrent events.",
    source: "california",
    status: "signed",
    statusLabel: "Signed into Law",
    statusDate: "2025-02-01",
    introducedDate: "2025-01-14",
    body: "California Senate – Second Extraordinary Session",
    sponsors: [{ name: "Caballero", party: "D" }],
    topics: ["disaster_relief", "wildfire_recovery"],
    url: "https://leginfo.legislature.ca.gov/faces/billTextClient.xhtml?bill_id=202520260SBX21",
    summary:
      "Emergency spending and coordination authority as part of the Second Extraordinary Session called in response to the January 2025 Los Angeles wildfires.",
    lastAction: "Signed by Governor Newsom",
    isHighlighted: true,
    relevanceScore: 9,
  },
  {
    id: "ca-abx2-7",
    billNumber: "ABX2 7",
    title: "FAIR Plan Expansion and Wildfire Insurance Reform",
    description:
      "Requires the California FAIR Plan to expand coverage limits, improve policy processing times, and make emergency payouts faster after a declared wildfire disaster. Responds directly to insurer pullbacks in high-risk areas like Altadena.",
    source: "california",
    status: "in_committee",
    statusLabel: "In Committee",
    statusDate: "2025-02-10",
    introducedDate: "2025-01-16",
    body: "California Assembly – Second Extraordinary Session",
    sponsors: [{ name: "Ting", party: "D" }],
    topics: ["insurance", "wildfire_recovery"],
    url: "https://leginfo.legislature.ca.gov/faces/billSearchClient.xhtml",
    summary:
      "Targets the California FAIR Plan (insurer of last resort) following mass cancellations by private insurers in wildfire-prone areas. Increases required coverage limits and mandates faster claims processing.",
    lastAction: "Referred to Insurance Committee",
    isHighlighted: true,
    relevanceScore: 10,
  },
  {
    id: "ca-sbx2-4",
    billNumber: "SBX2 4",
    title: "Utility Wildfire Liability and Inverse Condemnation Reform",
    description:
      "Modifies the liability standard for investor-owned utilities whose equipment causes wildfires, and establishes a state wildfire fund backstop. A response to ongoing debates about PG&E-style liability in the context of the 2025 LA fires.",
    source: "california",
    status: "in_committee",
    statusLabel: "In Committee",
    statusDate: "2025-02-12",
    introducedDate: "2025-01-17",
    body: "California Senate – Second Extraordinary Session",
    sponsors: [{ name: "Dodd", party: "D" }],
    topics: ["utilities", "wildfire_recovery", "public_safety"],
    url: "https://leginfo.legislature.ca.gov/faces/billSearchClient.xhtml",
    summary:
      "Addresses the doctrine of inverse condemnation as applied to utility-caused wildfires, attempting to balance ratepayer protection with accountability for utility companies.",
    lastAction: "Referred to Energy Committee",
    relevanceScore: 7,
  },

  // ── CALIFORNIA REGULAR SESSION (2025) ────────────────────────────────────────

  {
    id: "ca-ab-1642",
    billNumber: "AB 1642",
    title: "Wildfire Contamination: DTSC Health-Based Clearance Standards",
    description:
      "Requires the Department of Toxic Substances Control (DTSC) to adopt emergency regulations by July 1, 2027 specifying standards for investigation, environmental testing, and removal of contaminants inside and outside homes, schools, and workplaces in residential areas after a wildfire. Standards must include health-based clearance levels.",
    source: "california",
    status: "in_committee",
    statusLabel: "In Committee",
    statusDate: "2025-02-01",
    introducedDate: "2025-01-13",
    body: "California Assembly",
    sponsors: [],
    topics: ["wildfire_recovery", "public_safety", "debris_removal"],
    url: "https://leginfo.legislature.ca.gov/faces/billNavClient.xhtml?bill_id=202520260AB1642",
    summary:
      "Directly addresses one of the most serious long-term risks facing Altadena residents: toxic contamination from ash, heavy metals, and hazardous materials left behind by the Eaton Fire. Mandates DTSC set enforceable, health-based clearance standards before homes are re-occupied — a gap in current law exposed by the 2025 fires.",
    lastAction: "Referred to Committee",
    isHighlighted: true,
    relevanceScore: 10,
  },
  {
    id: "ca-ab-238",
    billNumber: "AB 238",
    title: "Wildfire Mortgage Forbearance: Eaton and Palisades Fire Relief",
    description:
      "Authorizes borrowers experiencing financial hardship due directly to the Eaton Wildfire, Palisades Fire, or Straight-line Winds (January 2025 state of emergency / federal disaster declaration) to request forbearance on residential mortgage loans, with prescribed procedures for lenders.",
    source: "california",
    status: "in_committee",
    statusLabel: "In Committee",
    statusDate: "2025-01-27",
    introducedDate: "2025-01-13",
    body: "California Assembly",
    sponsors: [],
    topics: ["housing", "disaster_relief", "wildfire_recovery"],
    url: "https://leginfo.legislature.ca.gov/faces/billNavClient.xhtml?bill_id=202520260AB238",
    summary:
      "Many Altadena homeowners who lost income or their homes in the Eaton Fire are still carrying mortgages on destroyed or uninhabitable properties. This bill creates a formal forbearance process tied specifically to the January 2025 disaster declarations, preventing foreclosure during the recovery period.",
    lastAction: "Referred to Committee",
    isHighlighted: true,
    relevanceScore: 10,
  },
  {
    id: "ca-ab-226",
    billNumber: "AB 226",
    title: "Homeowner Insurance: Non-Renewal Moratorium in Disaster Areas",
    description:
      "Extends the moratorium on insurance non-renewals and cancellations for properties within or near a declared wildfire disaster area from one year to two years, and expands the geographic coverage of the moratorium.",
    source: "california",
    status: "in_committee",
    statusLabel: "In Committee",
    statusDate: "2025-02-15",
    introducedDate: "2025-01-13",
    body: "California Assembly",
    sponsors: [{ name: "Muratsuchi", party: "D" }],
    topics: ["insurance", "wildfire_recovery", "housing"],
    url: "https://leginfo.legislature.ca.gov/faces/billSearchClient.xhtml",
    summary:
      "Extends protections against insurance cancellation for homeowners in declared disaster zones, directly relevant to Altadena residents affected by the Eaton Fire.",
    lastAction: "Referred to Assembly Insurance Committee",
    isHighlighted: true,
    relevanceScore: 10,
  },
  {
    id: "ca-sb-505",
    billNumber: "SB 505",
    title: "FAIR Plan: Mandatory Coverage Increases",
    description:
      "Requires the California FAIR Plan to increase its maximum dwelling coverage limits to reflect current construction costs, and bans the use of pre-loss property values to limit payouts for total losses.",
    source: "california",
    status: "in_committee",
    statusLabel: "In Committee",
    statusDate: "2025-02-10",
    introducedDate: "2025-01-16",
    body: "California Senate",
    sponsors: [{ name: "Wahab", party: "D" }],
    topics: ["insurance", "wildfire_recovery"],
    url: "https://leginfo.legislature.ca.gov/faces/billSearchClient.xhtml",
    summary:
      "Many Altadena homeowners on the FAIR Plan discovered their coverage was far below actual rebuild costs. This bill addresses the coverage gap by requiring updated limits.",
    lastAction: "Referred to Senate Insurance Committee",
    isHighlighted: true,
    relevanceScore: 9,
  },
  {
    id: "ca-ab-1054",
    billNumber: "AB 1054",
    title: "Wildfire Fund: Extension and Reform (Follow-up)",
    description:
      "Proposes amendments to the California Wildfire Fund established in 2019, extending its term and revising contribution requirements for utilities in light of increased wildfire frequency.",
    source: "california",
    status: "introduced",
    statusLabel: "Introduced",
    statusDate: "2025-01-20",
    introducedDate: "2025-01-20",
    body: "California Assembly",
    sponsors: [{ name: "Holden", party: "D" }],
    topics: ["utilities", "wildfire_recovery", "environment"],
    url: "https://leginfo.legislature.ca.gov/faces/billSearchClient.xhtml",
    summary:
      "Extends the 2019 wildfire fund created after the PG&E fires, addressing concerns about fund solvency given the scale of 2025 losses.",
    lastAction: "Introduced",
    relevanceScore: 6,
  },
  {
    id: "ca-sb-222",
    billNumber: "SB 222",
    title: "Expedited Permitting for Wildfire Reconstruction",
    description:
      "Requires local governments in disaster-declared areas to issue building permits for like-for-like reconstruction within 30 days, and prohibits new zoning restrictions that would prevent reconstruction of destroyed structures.",
    source: "california",
    status: "in_committee",
    statusLabel: "In Committee",
    statusDate: "2025-02-12",
    introducedDate: "2025-01-21",
    body: "California Senate",
    sponsors: [{ name: "Glazer", party: "D" }],
    topics: ["rebuilding", "wildfire_recovery", "housing"],
    url: "https://leginfo.legislature.ca.gov/faces/billSearchClient.xhtml",
    summary:
      "Directly addresses one of the major barriers to Altadena recovery: slow permitting. Requires 30-day turnaround on like-for-like rebuild permits.",
    lastAction: "Referred to Senate Governance and Finance Committee",
    isHighlighted: true,
    relevanceScore: 10,
  },
  {
    id: "ca-ab-302",
    billNumber: "AB 302",
    title: "Wildfire Home Hardening Tax Credit",
    description:
      "Creates a state income tax credit for homeowners who invest in fire-hardening improvements (ember-resistant vents, Class A roofing, defensible space improvements) in high-risk fire zones.",
    source: "california",
    status: "introduced",
    statusLabel: "Introduced",
    statusDate: "2025-01-22",
    introducedDate: "2025-01-22",
    body: "California Assembly",
    sponsors: [{ name: "Flora", party: "R" }],
    topics: ["wildfire_recovery", "housing", "environment"],
    url: "https://leginfo.legislature.ca.gov/faces/billSearchClient.xhtml",
    summary:
      "Tax incentive for fire-resistant home improvements, aimed at both existing homeowners and those rebuilding after the 2025 fires.",
    lastAction: "Referred to Assembly Revenue and Taxation Committee",
    relevanceScore: 7,
  },
  {
    id: "ca-sb-9-2025",
    billNumber: "SB 9 (2025 Extr.)",
    title: "Local Zoning Override for Fire Rebuild: ADU and Density",
    description:
      "Allows homeowners in wildfire disaster areas to rebuild with accessory dwelling units (ADUs) or at higher densities without local approval, overriding restrictive zoning to accelerate housing recovery.",
    source: "california",
    status: "in_committee",
    statusLabel: "In Committee",
    statusDate: "2025-02-08",
    introducedDate: "2025-01-18",
    body: "California Senate – Second Extraordinary Session",
    sponsors: [{ name: "Wiener", party: "D" }],
    topics: ["housing", "rebuilding", "wildfire_recovery"],
    url: "https://leginfo.legislature.ca.gov/faces/billSearchClient.xhtml",
    summary:
      "Addresses Altadena-specific concerns about Measure A-type restrictions and local zoning preventing denser rebuild. Allows disaster victims to rebuild with additional units.",
    lastAction: "Referred to Senate Housing Committee",
    isHighlighted: true,
    relevanceScore: 9,
  },
  {
    id: "ca-ab-fire-insurance-reform",
    billNumber: "AB 1493 (2025)",
    title: "Insurance Commissioner: Wildfire Risk Pricing Transparency",
    description:
      "Requires insurers operating in California to disclose their wildfire risk models to the Insurance Commissioner and provide detailed explanations when canceling or non-renewing policies, with enhanced transparency for policyholders.",
    source: "california",
    status: "introduced",
    statusLabel: "Introduced",
    statusDate: "2025-01-28",
    introducedDate: "2025-01-28",
    body: "California Assembly",
    sponsors: [{ name: "Cervantes", party: "D" }],
    topics: ["insurance", "wildfire_recovery"],
    url: "https://leginfo.legislature.ca.gov/faces/billSearchClient.xhtml",
    summary:
      "Responds to the sudden insurance withdrawals from high-risk areas (including Altadena) by requiring transparency in the models insurers use to justify cancellations.",
    lastAction: "Introduced",
    relevanceScore: 8,
  },
  {
    id: "ca-newsom-regulation-insurance",
    billNumber: "Reg. Action",
    title: "California DOI: Catastrophe Reinsurance Allowance Rule (Lara Rule)",
    description:
      "A regulatory action (not a bill) by the California Department of Insurance under Commissioner Lara allowing insurers to use forward-looking catastrophe models and factor in reinsurance costs when setting rates — with the expectation they maintain coverage in high-risk areas.",
    source: "california",
    status: "enacted",
    statusLabel: "Enacted (Regulatory)",
    statusDate: "2025-01-01",
    introducedDate: "2024-12-01",
    body: "California Department of Insurance",
    sponsors: [{ name: "Ricardo Lara", party: "D" }],
    topics: ["insurance", "wildfire_recovery"],
    url: "https://www.insurance.ca.gov/0400-news/0100-press-releases/2024/",
    summary:
      "Regulatory change (Proposition 103 implementation) that took effect January 1, 2025 aimed at enticing insurers back to California by letting them price for catastrophe risk. Its implementation timing has been controversial given the Eaton Fire.",
    lastAction: "Rule effective January 1, 2025",
    isHighlighted: true,
    relevanceScore: 9,
  },

  // ── CALIFORNIA SENATE — FIRE SAFE CALIFORNIA PACKAGE (2025) ─────────────────

  {
    id: "ca-sb-581",
    billNumber: "SB 581",
    title: "Fight For Firefighters Act of 2025: CAL FIRE Seasonal-to-Permanent",
    description:
      "Transitions all 3,000 nine-month seasonal CAL FIRE firefighters to year-round permanent positions. Fully staffs all 356 CAL FIRE fire engines and all heli-attack bases 365 days per year while keeping vegetation management crews working for a full 12 months.",
    source: "california",
    status: "in_committee",
    statusLabel: "In Committee",
    statusDate: "2025-02-01",
    introducedDate: "2025-01-13",
    body: "California Senate",
    sponsors: [
      { name: "McGuire", party: "D" },
      { name: "Grayson", party: "D" },
      { name: "Allen", party: "D" },
      { name: "Pérez", party: "D" },
    ],
    topics: ["wildfire_recovery", "public_safety"],
    url: "https://leginfo.legislature.ca.gov/faces/billNavClient.xhtml?bill_id=202520260SB581",
    summary:
      "CAL FIRE's seasonal staffing gaps have long been identified as a wildfire suppression vulnerability. Making these positions permanent keeps engines and crews deployed year-round — critical given that California's fire season is now effectively 12 months.",
    lastAction: "Referred to Committee",
    isHighlighted: true,
    relevanceScore: 8,
  },
  {
    id: "ca-sb-36",
    billNumber: "SB 36",
    title: "Price Gouging: Civil Penalties and Online Platform Accountability",
    description:
      "Curbs price gouging by adding civil remedies and penalties to protect victims displaced by a state or local emergency. Enhances enforcement for housing, lodging, and rental violations by authorizing AG warrant authority and requiring online housing platforms to provide evidence of price gouging to law enforcement.",
    source: "california",
    status: "in_committee",
    statusLabel: "In Committee",
    statusDate: "2025-02-01",
    introducedDate: "2025-01-09",
    body: "California Senate",
    sponsors: [
      { name: "Umberg", party: "D" },
      { name: "Smallwood-Cuevas", party: "D" },
    ],
    topics: ["disaster_relief", "housing", "wildfire_recovery"],
    url: "https://leginfo.legislature.ca.gov/faces/billNavClient.xhtml?bill_id=202520260SB36",
    summary:
      "Directly relevant to Altadena displaced residents who faced rent and housing price spikes after the Eaton Fire. Gives the AG stronger tools to prosecute landlords and platforms (Airbnb, Zillow, etc.) that exploit disaster victims.",
    lastAction: "Referred to Committee",
    isHighlighted: true,
    relevanceScore: 9,
  },
  {
    id: "ca-sb-610",
    billNumber: "SB 610",
    title: "Expanded Protections for Residents After Emergency: Forbearance, Rent, Mobilehomes",
    description:
      "Requires the State to convene mortgage companies to provide temporary forbearance relief for homeowners. Allows tenants to recover a proportion of paid rent if a tenancy terminates due to wildfire. Establishes temporary rent control for mobilehomes in emergency areas. Grants mobilehome owners the right to return after wildfire. Extends court timelines for unlawful detainer cases in emergency areas.",
    source: "california",
    status: "in_committee",
    statusLabel: "In Committee",
    statusDate: "2025-02-01",
    introducedDate: "2025-01-13",
    body: "California Senate",
    sponsors: [
      { name: "Pérez", party: "D" },
      { name: "Allen", party: "D" },
      { name: "Wahab", party: "D" },
    ],
    topics: ["housing", "disaster_relief", "wildfire_recovery"],
    url: "https://leginfo.legislature.ca.gov/faces/billNavClient.xhtml?bill_id=202520260SB610",
    summary:
      "A broad housing protection package covering Altadena residents across tenures: renters, homeowners, and mobilehome residents. The state-convened forbearance mechanism differs from AB 238's direct authorization, focusing on coordinating lender agreements at scale.",
    lastAction: "Referred to Committee",
    isHighlighted: true,
    relevanceScore: 10,
  },
  {
    id: "ca-sb-663",
    billNumber: "SB 663",
    title: "Property Tax Relief Following the 2025 Southern California Fires",
    description:
      "Ensures damaged or destroyed properties maintain their welfare property tax exemption. Extends the timeline for taxpayers to file a misfortune and calamity claim. Extends from 5 to 8 years the period to rebuild after a wildfire without triggering property tax reassessment.",
    source: "california",
    status: "in_committee",
    statusLabel: "In Committee",
    statusDate: "2025-02-01",
    introducedDate: "2025-01-13",
    body: "California Senate",
    sponsors: [
      { name: "Allen", party: "D" },
      { name: "McNerney", party: "D" },
      { name: "Pérez", party: "D" },
    ],
    topics: ["disaster_relief", "wildfire_recovery", "rebuilding"],
    url: "https://leginfo.legislature.ca.gov/faces/billNavClient.xhtml?bill_id=202520260SB663",
    summary:
      "Altadena property owners face property tax bills on land where their homes no longer exist, and many cannot rebuild within the current 5-year window without triggering reassessment. This bill extends relief on both fronts.",
    lastAction: "Referred to Committee",
    isHighlighted: true,
    relevanceScore: 10,
  },
  {
    id: "ca-sb-625",
    billNumber: "SB 625",
    title: "Speed-Up Residential Rebuilds Following a State of Emergency",
    description:
      "Requires local governments to provide streamlined ministerial approval of housing developments damaged in a declared emergency, removing discretionary review barriers that slow reconstruction.",
    source: "california",
    status: "in_committee",
    statusLabel: "In Committee",
    statusDate: "2025-02-01",
    introducedDate: "2025-01-13",
    body: "California Senate",
    sponsors: [
      { name: "Wahab", party: "D" },
      { name: "Richardson", party: "D" },
    ],
    topics: ["rebuilding", "housing", "wildfire_recovery"],
    url: "https://leginfo.legislature.ca.gov/faces/billNavClient.xhtml?bill_id=202520260SB625",
    summary:
      "Complements existing fast-permitting bills by mandating ministerial (by-right) approval — removing local planning commission discretion — for rebuilding in declared disaster areas like Altadena.",
    lastAction: "Referred to Committee",
    isHighlighted: true,
    relevanceScore: 10,
  },
  {
    id: "ca-sb-616",
    billNumber: "SB 616",
    title: "Insurance Community Hardening Commission: Statewide Fire Standards",
    description:
      "Establishes an Insurance Community Hardening Commission to create consistent, data-driven statewide minimum fire mitigation standards for high-fire-risk communities. Centralizes standards to make it easier for homeowners, developers, and builders to comply and easier for homeowners to obtain insurance.",
    source: "california",
    status: "in_committee",
    statusLabel: "In Committee",
    statusDate: "2025-02-01",
    introducedDate: "2025-01-13",
    body: "California Senate",
    sponsors: [
      { name: "Rubio", party: "D" },
      { name: "Cortese", party: "D" },
      { name: "Stern", party: "D" },
    ],
    topics: ["insurance", "wildfire_recovery", "public_safety"],
    url: "https://leginfo.legislature.ca.gov/faces/billNavClient.xhtml?bill_id=202520260SB616",
    summary:
      "Addresses the fragmented patchwork of fire hardening requirements that vary by insurer and jurisdiction. A unified standard could make it clearer what Altadena residents rebuilding must do to qualify for private insurance.",
    lastAction: "Referred to Committee",
    relevanceScore: 8,
  },
  {
    id: "ca-sb-547",
    billNumber: "SB 547",
    title: "Commercial Insurance Nonrenewal Moratorium",
    description:
      "Expands the existing one-year insurance non-renewal moratorium — currently limited to residential policies — to also cover commercial policies within the perimeters or adjoining ZIP codes of wildfires. Protects small businesses and condominiums.",
    source: "california",
    status: "in_committee",
    statusLabel: "In Committee",
    statusDate: "2025-02-01",
    introducedDate: "2025-01-13",
    body: "California Senate",
    sponsors: [
      { name: "Pérez", party: "D" },
      { name: "Rubio", party: "D" },
    ],
    topics: ["insurance", "wildfire_recovery"],
    url: "https://leginfo.legislature.ca.gov/faces/billNavClient.xhtml?bill_id=202520260SB547",
    summary:
      "Altadena's commercial corridors (Lake Ave, Lincoln Ave) face the same insurer pullback as residential areas. This bill closes the loophole that left small businesses and condo associations without the same post-fire moratorium protection as homeowners.",
    lastAction: "Referred to Committee",
    relevanceScore: 8,
  },
  {
    id: "ca-sb-676",
    billNumber: "SB 676",
    title: "CEQA Streamlining for LA Fires and Other Disaster Rebuilds",
    description:
      "Extends the same CEQA streamlining already available for major infrastructure projects to projects rebuilding communities after the 2025 LA wildfires. Applies both prospectively and retroactively, potentially removing months or years from environmental review for planned rebuilds.",
    source: "california",
    status: "in_committee",
    statusLabel: "In Committee",
    statusDate: "2025-02-01",
    introducedDate: "2025-01-13",
    body: "California Senate",
    sponsors: [
      { name: "Limón", party: "D" },
      { name: "Blakespear", party: "D" },
    ],
    topics: ["rebuilding", "wildfire_recovery", "environment"],
    url: "https://leginfo.legislature.ca.gov/faces/billNavClient.xhtml?bill_id=202520260SB676",
    summary:
      "CEQA review is one of the most cited causes of reconstruction delay. This bill fast-tracks environmental review specifically for post-fire rebuilds, applying retroactively to projects already in the pipeline.",
    lastAction: "Referred to Committee",
    isHighlighted: true,
    relevanceScore: 9,
  },
  {
    id: "ca-sb-582",
    billNumber: "SB 582",
    title: "Rebuilding Licensed Health, Child Care, and Assisted Living Facilities",
    description:
      "Assists state-licensed facilities (health facilities, assisted living, child care) on their path to recovery by streamlining licensing processes and authorizing departments to waive licensing fees and other requirements for facilities rebuilding after a disaster.",
    source: "california",
    status: "in_committee",
    statusLabel: "In Committee",
    statusDate: "2025-02-01",
    introducedDate: "2025-01-13",
    body: "California Senate",
    sponsors: [{ name: "Stern", party: "D" }],
    topics: ["rebuilding", "wildfire_recovery", "public_safety"],
    url: "https://leginfo.legislature.ca.gov/faces/billNavClient.xhtml?bill_id=202520260SB582",
    summary:
      "Altadena lost child care facilities, elder care services, and health clinics in the Eaton Fire. This bill removes licensing red tape that would otherwise delay their reopening.",
    lastAction: "Referred to Committee",
    relevanceScore: 7,
  },
  {
    id: "ca-sb-571",
    billNumber: "SB 571",
    title: "Strengthen Penalties for Looting, Impersonation, and Arson During Emergencies",
    description:
      "Increases penalties for impersonating firefighters and other first responders, and for looting in a fire evacuation area. Ensures that an aggravated arson sentencing enhancement attaches to damage amounts at the time of the crime.",
    source: "california",
    status: "in_committee",
    statusLabel: "In Committee",
    statusDate: "2025-02-01",
    introducedDate: "2025-01-13",
    body: "California Senate",
    sponsors: [
      { name: "Archuleta", party: "D" },
      { name: "Arreguín", party: "D" },
    ],
    topics: ["public_safety", "disaster_relief"],
    url: "https://leginfo.legislature.ca.gov/faces/billNavClient.xhtml?bill_id=202520260SB571",
    summary:
      "Responds to documented looting in evacuated Altadena neighborhoods and impersonation incidents during the Eaton Fire. Increases criminal deterrents against taking advantage of disaster victims.",
    lastAction: "Referred to Committee",
    relevanceScore: 7,
  },
  {
    id: "ca-sb-629",
    billNumber: "SB 629",
    title: "Keeping Communities Safe From Wildfires: Hazard Zone Designation and Inspections",
    description:
      "Requires local governments to designate areas that burn in a wildfire as within Very High Fire Hazard Severity Zones. Mandates annual inspection of properties subject to defensible space requirements. Requires CAL FIRE to account for urban wildfire risk in the next fire hazard severity map update.",
    source: "california",
    status: "in_committee",
    statusLabel: "In Committee",
    statusDate: "2025-02-01",
    introducedDate: "2025-01-13",
    body: "California Senate",
    sponsors: [{ name: "Durazo", party: "D" }],
    topics: ["public_safety", "wildfire_recovery", "environment"],
    url: "https://leginfo.legislature.ca.gov/faces/billNavClient.xhtml?bill_id=202520260SB629",
    summary:
      "Much of Altadena was not designated Very High Fire Hazard Severity prior to the Eaton Fire, leaving residents without certain hardening requirements and insurance protections that come with that designation. This bill ensures burned communities get that designation automatically.",
    lastAction: "Referred to Committee",
    relevanceScore: 8,
  },
  {
    id: "ca-sb-326",
    billNumber: "SB 326",
    title: "California Wildfire Mitigation Strategic Planning Act",
    description:
      "Requires the State Fire Marshal to prepare a Wildfire Risk Mitigation Planning Framework every three years to quantitatively evaluate risk mitigation actions. Establishes a statewide Wildfire Risk Baseline and Forecast by county every three years, and an annual Wildfire Mitigation Scenarios Report.",
    source: "california",
    status: "in_committee",
    statusLabel: "In Committee",
    statusDate: "2025-02-01",
    introducedDate: "2025-01-13",
    body: "California Senate",
    sponsors: [
      { name: "Becker", party: "D" },
      { name: "Laird", party: "D" },
    ],
    topics: ["wildfire_recovery", "environment", "public_safety"],
    url: "https://leginfo.legislature.ca.gov/faces/billNavClient.xhtml?bill_id=202520260SB326",
    summary:
      "Creates a data-driven planning infrastructure to systematically evaluate and report on California's wildfire mitigation progress — ensuring the response to the 2025 fires translates into measurable, accountable long-term risk reduction.",
    lastAction: "Referred to Committee",
    relevanceScore: 6,
  },
  {
    id: "ca-sb-641",
    billNumber: "SB 641",
    title: "Consumer Protection and Business Recovery After Wildfire",
    description:
      "Protects consumers by establishing timelines and certifications for debris removal and prohibiting unsolicited property purchase offers in disaster areas. Protects licensed professionals by waiving licensure requirements (continuing education, fees, renewal deadlines) when impacted by a wildfire or natural disaster.",
    source: "california",
    status: "in_committee",
    statusLabel: "In Committee",
    statusDate: "2025-02-01",
    introducedDate: "2025-01-13",
    body: "California Senate",
    sponsors: [{ name: "Ashby", party: "D" }],
    topics: ["debris_removal", "disaster_relief", "wildfire_recovery"],
    url: "https://leginfo.legislature.ca.gov/faces/billNavClient.xhtml?bill_id=202520260SB641",
    summary:
      "Targets two known post-disaster problems in Altadena: fly-by-night debris contractors with no accountability, and land speculators making unsolicited lowball offers to traumatized homeowners. Also helps displaced professionals (doctors, contractors, teachers) maintain their licenses during recovery.",
    lastAction: "Referred to Committee",
    isHighlighted: true,
    relevanceScore: 9,
  },

  // ── CALIFORNIA BUDGET PROPOSALS (2025 Southern California Fires) ─────────────

  {
    id: "ca-budget-fire-relief-displaced",
    billNumber: "Budget Proposal",
    title: "Fire Relief Aid for Displaced Persons (2025 Budget)",
    description:
      "Establishes a one-time disaster relief fund for families and individuals impacted by the 2025 Southern California fires who are unable to obtain assistance from other funding streams, including FEMA Individual Assistance.",
    source: "california",
    status: "proposed",
    statusLabel: "Budget Proposal",
    statusDate: "2025-02-01",
    introducedDate: "2025-01-13",
    body: "California Legislature – Budget",
    sponsors: [],
    topics: ["disaster_relief", "wildfire_recovery", "fema"],
    url: "https://democrats.senate.ca.gov/firesafe-california",
    summary:
      "A last-resort safety net for Altadena residents who fall through the gaps of federal programs. FEMA IA denials have been widespread; this state fund would provide relief to those who cannot access federal aid.",
    lastAction: "Proposed in Governor's budget package",
    isHighlighted: true,
    relevanceScore: 10,
  },
  {
    id: "ca-budget-displaced-tk12",
    billNumber: "Budget Proposal",
    title: "Supporting Displaced TK-12 Students (2025 Budget)",
    description:
      "Provides average daily attendance funding to schools that lost students due to the wildfire disaster. Provides disaster relief to basic aid school districts enrolling displaced students to ensure a quality education during the transition period.",
    source: "california",
    status: "proposed",
    statusLabel: "Budget Proposal",
    statusDate: "2025-02-01",
    introducedDate: "2025-01-13",
    body: "California Legislature – Budget",
    sponsors: [],
    topics: ["disaster_relief", "wildfire_recovery"],
    url: "https://democrats.senate.ca.gov/firesafe-california",
    summary:
      "Altadena's school-age children have been displaced into schools across the region. ADA funding follows the student — but the receiving schools weren't budgeted for these enrollments. This proposal holds harmless both the sending and receiving districts.",
    lastAction: "Proposed in Governor's budget package",
    relevanceScore: 8,
  },
  {
    id: "ca-budget-community-colleges",
    billNumber: "Budget Proposal",
    title: "Support for Impacted California Community Colleges (2025 Budget)",
    description:
      "Provides enrollment protections to maintain consistent funding for community colleges affected by the 2025 wildfires that may experience funding reductions due to declining enrollment during the disaster recovery period.",
    source: "california",
    status: "proposed",
    statusLabel: "Budget Proposal",
    statusDate: "2025-02-01",
    introducedDate: "2025-01-13",
    body: "California Legislature – Budget",
    sponsors: [],
    topics: ["disaster_relief", "wildfire_recovery"],
    url: "https://democrats.senate.ca.gov/firesafe-california",
    summary:
      "Pasadena City College serves much of the Altadena community. Enrollment drops from displaced students and faculty would normally trigger state funding cuts; this proposal holds colleges harmless during the recovery period.",
    lastAction: "Proposed in Governor's budget package",
    relevanceScore: 7,
  },

  // ── FEDERAL LEGISLATION (119th Congress, 2025) ───────────────────────────────

  {
    id: "fed-fema-reform-2025",
    billNumber: "HR 1024",
    title: "FEMA Modernization and Accountability Act of 2025",
    description:
      "Proposes significant reforms to FEMA's structure, including separating its disaster response and preparedness functions, establishing a National Disaster Recovery Administration, and creating new standards for disaster declarations.",
    source: "federal",
    status: "introduced",
    statusLabel: "Introduced",
    statusDate: "2025-02-03",
    introducedDate: "2025-02-03",
    body: "U.S. House of Representatives",
    sponsors: [
      { name: "Rep. Garcia (CA)", party: "D", state: "CA" },
    ],
    topics: ["fema", "disaster_relief"],
    url: "https://www.congress.gov/bill/119th-congress/house-bill/1024",
    summary:
      "Sweeping FEMA reorganization bill introduced in response to criticism of FEMA's handling of the 2024-2025 disaster season including the LA fires.",
    lastAction: "Referred to House Transportation & Infrastructure Committee",
    relevanceScore: 7,
  },
  {
    id: "fed-disaster-tax-relief-2025",
    billNumber: "HR 517 / S 212",
    title: "Disaster Tax Relief Act of 2025",
    description:
      "Provides temporary tax relief for individuals and businesses in federally declared disaster areas, including waiver of the 10% early withdrawal penalty on retirement accounts, enhanced casualty loss deductions, and employer retention credits.",
    source: "federal",
    status: "in_committee",
    statusLabel: "In Committee",
    statusDate: "2025-02-01",
    introducedDate: "2025-01-23",
    body: "U.S. Congress (House & Senate)",
    sponsors: [
      { name: "Rep. Panetta (CA)", party: "D", state: "CA" },
      { name: "Sen. Padilla (CA)", party: "D", state: "CA" },
    ],
    topics: ["disaster_relief", "wildfire_recovery"],
    url: "https://www.congress.gov/bill/119th-congress/house-bill/517",
    summary:
      "Directly applicable to Altadena residents who lost their homes in the Eaton Fire. Would allow penalty-free retirement withdrawals and enhanced deductions for uninsured losses.",
    lastAction: "Referred to Ways and Means / Finance Committees",
    isHighlighted: true,
    relevanceScore: 10,
  },
  {
    id: "fed-fema-flood-wildfire",
    billNumber: "S 318",
    title: "Wildfire and Flood Insurance Act",
    description:
      "Proposes creating a federal wildfire insurance backstop program modeled on the National Flood Insurance Program (NFIP), providing federally backed coverage for homeowners in high wildfire risk areas where private insurance is unavailable.",
    source: "federal",
    status: "introduced",
    statusLabel: "Introduced",
    statusDate: "2025-01-29",
    introducedDate: "2025-01-29",
    body: "U.S. Senate",
    sponsors: [
      { name: "Sen. Padilla (CA)", party: "D", state: "CA" },
      { name: "Sen. Feinstein successor", party: "D", state: "CA" },
    ],
    topics: ["insurance", "fema", "wildfire_recovery", "disaster_relief"],
    url: "https://www.congress.gov/bill/119th-congress/senate-bill/318",
    summary:
      "A transformative proposal to create a federal wildfire insurance program. If enacted, would provide a safety net for homeowners like those in Altadena who lost private insurance coverage before the fires.",
    lastAction: "Referred to Senate Banking Committee",
    isHighlighted: true,
    relevanceScore: 9,
  },
  {
    id: "fed-community-development-block",
    billNumber: "Appropriations",
    title: "CDBG-DR: Community Development Block Grant – Disaster Recovery",
    description:
      "HUD's CDBG-DR program (not a new bill but appropriated funds) provides flexible disaster recovery grants to states. Congress is considering supplemental appropriations for the 2025 LA fires. Los Angeles County and California would receive funding for long-term housing and economic recovery.",
    source: "federal",
    status: "proposed",
    statusLabel: "Supplemental Appropriation Proposed",
    statusDate: "2025-02-10",
    introducedDate: "2025-02-01",
    body: "U.S. Congress – Appropriations",
    sponsors: [
      { name: "Rep. Lieu (CA)", party: "D", state: "CA" },
      { name: "Sen. Padilla (CA)", party: "D", state: "CA" },
    ],
    topics: ["disaster_relief", "housing", "rebuilding", "wildfire_recovery"],
    url: "https://www.hud.gov/program_offices/comm_planning/cdbg-dr",
    summary:
      "HUD disaster recovery block grants are often the single largest source of long-term rebuilding money for communities. A supplemental CDBG-DR appropriation for the LA fires is being pushed by the California delegation.",
    lastAction: "California delegation requesting supplemental appropriation",
    isHighlighted: true,
    relevanceScore: 10,
  },
  {
    id: "fed-wildfire-resilience-act",
    billNumber: "S 427",
    title: "National Wildfire Resilience Act",
    description:
      "Establishes a federal-state cost-share program for wildfire mitigation, including defensible space programs, utility hardening, and community fire adaptation plans. Prioritizes communities in the wildland-urban interface (WUI) with demonstrated risk.",
    source: "federal",
    status: "introduced",
    statusLabel: "Introduced",
    statusDate: "2025-01-31",
    introducedDate: "2025-01-31",
    body: "U.S. Senate",
    sponsors: [
      { name: "Sen. Schiff (CA)", party: "D", state: "CA" },
    ],
    topics: ["wildfire_recovery", "environment", "public_safety", "utilities"],
    url: "https://www.congress.gov/bill/119th-congress/senate-bill/427",
    summary:
      "Proposes a sustained federal investment in wildfire prevention in communities like Altadena rather than only reacting after disasters. Includes utility hardening and defensible space grants.",
    lastAction: "Referred to Senate Energy and Natural Resources Committee",
    relevanceScore: 7,
  },
  {
    id: "fed-safe-rebuilding",
    billNumber: "HR 892",
    title: "Disaster Survivor Housing Security Act",
    description:
      "Expands FEMA's Transitional Sheltering Assistance (TSA) program, extends the maximum duration of hotel/motel assistance, creates a rent assistance bridge program for disaster survivors, and removes the income limits that exclude many Altadena homeowners.",
    source: "federal",
    status: "introduced",
    statusLabel: "Introduced",
    statusDate: "2025-02-05",
    introducedDate: "2025-02-05",
    body: "U.S. House of Representatives",
    sponsors: [
      { name: "Rep. Bass (CA)", party: "D", state: "CA" },
      { name: "Rep. Chu (CA)", party: "D", state: "CA" },
    ],
    topics: ["housing", "fema", "disaster_relief", "wildfire_recovery"],
    url: "https://www.congress.gov/bill/119th-congress/house-bill/892",
    summary:
      "A direct response to Eaton Fire survivors being denied FEMA housing assistance because they owned their homes (the Individuals and Households Program has gaps for homeowners). Expands TSA eligibility.",
    lastAction: "Referred to House Transportation & Infrastructure Committee",
    isHighlighted: true,
    relevanceScore: 10,
  },
  {
    id: "fed-forest-service-thinning",
    billNumber: "HR 670",
    title: "Protecting Communities from Wildfires Act",
    description:
      "Streamlines environmental review for fuel reduction treatments (thinning, prescribed burns) on federal and adjacent lands within 10 miles of communities in designated wildfire risk zones, with expedited NEPA review.",
    source: "federal",
    status: "in_committee",
    statusLabel: "In Committee",
    statusDate: "2025-02-15",
    introducedDate: "2025-01-28",
    body: "U.S. House of Representatives",
    sponsors: [
      { name: "Rep. LaMalfa (CA)", party: "R", state: "CA" },
    ],
    topics: ["wildfire_recovery", "environment", "public_safety"],
    url: "https://www.congress.gov/bill/119th-congress/house-bill/670",
    summary:
      "Bipartisan interest in expediting fuel management around communities. Though the Angeles National Forest is relevant to Altadena's exposure, this bill addresses the NEPA process more broadly.",
    lastAction: "Referred to House Natural Resources Committee",
    relevanceScore: 6,
  },
  {
    id: "fed-fema-ia-boost",
    billNumber: "HR 1101",
    title: "FEMA Individual Assistance Enhancement Act",
    description:
      "Increases the maximum FEMA Individual Assistance (IA) housing grant from approximately $43,900 to $150,000 and indexes it to inflation. Also removes bureaucratic barriers that caused many Eaton Fire survivors to be initially denied.",
    source: "federal",
    status: "introduced",
    statusLabel: "Introduced",
    statusDate: "2025-02-10",
    introducedDate: "2025-02-10",
    body: "U.S. House of Representatives",
    sponsors: [
      { name: "Rep. Lieu (CA)", party: "D", state: "CA" },
      { name: "Rep. Schiff (CA)", party: "D", state: "CA" },
    ],
    topics: ["fema", "disaster_relief", "housing", "wildfire_recovery"],
    url: "https://www.congress.gov/bill/119th-congress/house-bill/1101",
    summary:
      "FEMA's current maximum Individual Assistance grant (~$43,900) is far too low for the Altadena housing market. This bill raises the cap substantially and adjusts for inflation going forward.",
    lastAction: "Introduced",
    isHighlighted: true,
    relevanceScore: 10,
  },
];
